### ISSUE TITLE
Error: Snakefile "/Snakefile" not found.

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas_analyze#7]
When I run 

```
cd atlas_analyze
python analyze.py /scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS
```

I get 

```
Error: Snakefile "/Snakefile" not found.
Traceback (most recent call last):
  File "analyze.py", line 21, in <module>
    "snakemake "
  File "/scratch/gent/vo/000/gvo00043/vsc42339/conda/envs/analyze/lib/python3.7/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  snakemake -d /scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS -j 1 -s /Snakefile' returned non-zero exit status 1.

```

However, `atlas_analyze/Snakefile` does exist, but for some reason it does not find it. I tried copying it to the atlas working directory, but that didn't work

**Comment by slambrechts** [comment]
This might not be a proper way to fix this, but I was able to solve this for now by adding 

`-s ./Snakefile` to the 

`python analyze.py /scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS` command

First 2 out of 7 atlas_analyze steps finished successfully
