### ISSUE TITLE
Utils error

### ISSUE THREAD

**Issue by paleome** [metagenome-atlas/atlas_analyze#9]
Hi team, i am facing the error pasted below. This is a run that successfully completed in Atlas. Do you know what the problem is?

Traceback (most recent call last):
  File "/home/marco/miniconda3/atlas-testing/.snakemake/scripts/tmpgsvxn6_u.get_taxonomy.py", line 11, in <module>
    from utils.mag_scripts import tax2table
ModuleNotFoundError: No module named 'utils'
[Wed Sep 29 18:02:47 2021]
Error in rule get_taxonomy:
    jobid: 3
    output: Results/taxonomy.tsv

Traceback (most recent call last):
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2460, in run_wrapper
    raise ex
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2441, in run_wrapper
    runtime_sourcecache_path,
  File "/home/marco/miniconda3/atlas_analyze/Snakefile", line 97, in __rule_get_taxonomy
    "Results/mapping_rate.tsv"
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/script.py", line 1365, in script
    executor.evaluate()
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/script.py", line 377, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/script.py", line 578, in execute_script
    self._execute_cmd("{py_exec} {fname:q}", py_exec=py_exec, fname=fname)
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/script.py", line 421, in _execute_cmd
    **kwargs
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  /home/marco/miniconda3/envs/analyze/bin/python3.7 /home/marco/miniconda3/atlas-testing/.snakemake/scripts/tmpgsvxn6_u.get_taxonomy.py' returned non-zero exit status 1.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/marco/miniconda3/atlas-testing/.snakemake/log/2021-09-29T180246.949895.snakemake.log
Traceback (most recent call last):
  File "./analyze.py", line 21, in <module>
    "snakemake "
  File "/home/marco/miniconda3/envs/analyze/lib/python3.7/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  snakemake -d /home/marco/miniconda3/atlas-testing/ -j 1 -s ./Snakefile' returned non-zero exit status 1.

**Comment by SilasK** [comment]
I think atlas_analyze is no longer needed I implemented most of the steps in atlas v 2.8.1 together with the tutorial scripts in R and jupyter
